# Generated by Django 5.2.5 on 2026-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_campaign_complete_at_campaign_file_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pending_count',
            field=models.IntegerField(default=0),
        ),
    ]
